services:
  - type: web
    name: nestos-api
    env: node
    buildCommand: cd api && npm install && npm run build
    startCommand: cd api && npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_SESSION_URL
        sync: false
      - key: VAPID_PUBLIC_KEY
        value: BGORfzUeR-cwkiGC92fjkxOk_eHHC4EqMai1ucmD05Vaumoj1foXYoEbHxE8GPbjpX61mBto-_xv7YzPpkef1Wo
      - key: VAPID_PRIVATE_KEY
        value: 87VYpnCaZw9cjr3YEyqIH78MTJp_WlbMyrxIx-xk1n8
      - key: RENDER_EXTERNAL_URL
        value: https://nestos.onrender.com
