services:
  - type: web
    name: nestos-api
    env: node
    buildCommand: cd api && npm install && npm run build
    startCommand: cd api && npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_SESSION_URL
        sync: false
